/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author Manlio Tejeda Gutie
 */
public class administrador extends javax.swing.JFrame {

    public static String L[][] = new String[100][100], LG[][] = new String[100][100], ED[][] = new String[100][100], US[][] = new String[100][100],
            a1, a2, a3;
    public static int i = 10, CANTMATE[] = new int[5], cantED = 0, cantlib = 9, cantus = 0, cantlibtot = 9;
    public static int n2, n3, n4, n5, n6, n7, n8, n9, n10, r;
    public static double m;
    //cant mate tiene la cantidad de libros revista y monografia que hay

    /**
     * Creates new form administrador
     */
    public administrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldusuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        contraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("usuario administrador:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Contraseña:");

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        jLabel3.setText("Biblioteca La Sabiduria");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("x");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(contraseña)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel3)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTextFieldusuario.getText().equals("admin") & contraseña.getText().equals("admin")) {
            int c = 0;
            for (int j = 1; j <= 3; j++) {
                CANTMATE[j] = 0;
            }
            cantED = cantED + 1;
            ED[1][1] = "DON RAMON";
            ED[1][2] = Integer.toString(20154);

            menu a = new menu();
            a.setVisible(true);
            this.dispose();
            for (int i = 1; i <= 9; i++) {
                L[i][3] = Integer.toString(1 + c);
                c++;//VA DE 1-3
                switch (c) {
                    case 1:
                        CANTMATE[1] = CANTMATE[1] + 1;
                        LG[i][3] = "Libro";
                        L[i][3] = "Libro";
                        break;
                    case 2:
                        CANTMATE[2] = CANTMATE[2] + 1;
                        LG[i][3] = "Revista";
                        L[i][3] = "Revista";
                        break;
                    case 3:
                        CANTMATE[3] = CANTMATE[3] + 1;
                        LG[i][3] = "Monografia";
                        L[i][3] = "Monografia";
                        break;

                }

                if (c == 3) {
                    c = 0;
                }
                L[i][2] = Integer.toString(20154);
                L[i][5] = Integer.toString(1996 + c);
                L[i][6] = "La Constancia";
                L[i][7] = "bueno";
                L[i][8] = "no prestado";
                LG[i][2] = Integer.toString(20154);
                LG[i][5] = Integer.toString(1);
            }
            L[1][1] = "Como respirar";
            L[1][4] = "0201541998";
            L[2][1] = "Como aullar como perro";
            L[2][4] = "1201549744";
            L[3][1] = "Como dormir";
            L[3][4] = "2201545251";
            L[4][1] = "Como despertarse";
            L[4][4] = "0201544458";
            L[5][1] = "Como mover los dedos en el ser humano";
            L[5][4] = "12015470411";
            L[6][1] = "Como abrir una puerta";
            L[6][4] = "2201544921";
            L[7][1] = "Como cerrar una puerta";
            L[7][4] = "0201540355";
            L[8][1] = "Como mover la lengua en el ser humano";
            L[8][4] = "1201543894";
            L[9][1] = "Como caminar en el ser humano";
            L[9][4] = "2201541957";
            cantus = cantus + 1;
            US[cantus][1] = "ElBETA";
            US[cantus][2] = "200104288";
            US[cantus][3] = "como respirar";
            US[cantus][4] = "0201541998";
            US[cantus][5] = "1";
            LG[1][1] = "Como respirar";
            LG[1][4] = "0201541998";
            LG[2][1] = "Como aullar como perro";
            LG[2][4] = "1201549744";
            LG[3][1] = "Como dormir";
            LG[3][4] = "2201545251";
            LG[4][1] = "Como despertarse";
            LG[4][4] = "0201544458";
            LG[5][1] = "Como mover los dedos en el ser humano";
            LG[5][4] = "1201547041";
            LG[6][1] = "Como abrir una puerta";
            LG[6][4] = "2201544921";
            LG[7][1] = "Como cerrar una puerta";
            LG[7][4] = "0201540355";
            LG[8][1] = "Como mover la lengua en el ser humano";
            LG[8][4] = "1201543894";
            LG[9][1] = "Como caminar en el ser humano";
            LG[9][4] = "2201541957";

        } else {
            JOptionPane.showMessageDialog(null, "usuario y/o contraseña incorrecta");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contraseña;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldusuario;
    // End of variables declaration//GEN-END:variables
}
