/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.JOptionPane;
import static ventanas.administrador.*;

/**
 *
 * @author Manlio Tejeda Gutie
 */
public class adquisiciones extends javax.swing.JFrame {

    /**
     * Creates new form adquisiciones
     */
    public adquisiciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBoxadq = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldcoda = new javax.swing.JTextField();
        jTextFieldaño = new javax.swing.JTextField();
        jLabelaño = new javax.swing.JLabel();
        jTextFieldnombremat = new javax.swing.JTextField();
        jLabeleditoria = new javax.swing.JLabel();
        jTextFieldeditorial = new javax.swing.JTextField();
        jLabelISBN = new javax.swing.JLabel();
        jTextFieldISBN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxestado = new javax.swing.JComboBox<>();
        jButtonAceptar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxmaterial = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtcant = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Vivaldi", 1, 24)); // NOI18N
        jLabel3.setText("Biblioteca La Sabiduria");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("x");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBoxadq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Compra.", "Canje.", "Donacion." }));

        jLabel1.setText("Tipo De Adquisicion: ");

        jLabel2.setText("Codigo Del Autor:");

        jLabel5.setText("Nombre Del Material:");

        jLabelaño.setText("Año De Fabricacion:");

        jLabeleditoria.setText("Editorial:");

        jLabelISBN.setText("Codigo ISBN:");

        jLabel6.setText("Estado fisico (bueno o malo):");

        jComboBoxestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Bueno.", "Malo." }));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de material:");

        jComboBoxmaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro.", "Revista.", "Monografia." }));

        jLabel8.setText("Cantidad a Comprar:");

        jButton1.setText("menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelaño)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldaño, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addComponent(jComboBoxestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldcoda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldnombremat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabeleditoria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldeditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelISBN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(14, 14, 14))
                                    .addComponent(jComboBoxmaterial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jButtonAceptar)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jComboBoxadq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxadq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldcoda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldnombremat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelaño)
                                    .addComponent(jTextFieldaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel6)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeleditoria)
                            .addComponent(jTextFieldeditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelISBN)
                                    .addComponent(jTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButtonAceptar)
                .addGap(24, 24, 24)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        int adq, est, mat;
        adq = jComboBoxadq.getSelectedIndex();
        est = jComboBoxestado.getSelectedIndex();
        mat = jComboBoxmaterial.getSelectedIndex();
        if (adq == 0 || est == 0 || (jTextFieldeditorial.getText().equals("")) || (jTextFieldaño.getText().equals("")) || (jTextFieldcoda.getText().equals("")) || (jTextFieldnombremat.getText().equals("")) || (jTextFieldISBN.getText().equals("")) || (txtcant.getText().equals(""))) {
            JOptionPane.showMessageDialog(null, "llene todas las casillas ");
            if ((jTextFieldISBN.getText().equals("")) & adq == 1) {
                JOptionPane.showMessageDialog(null, "recuerde poner un 0 en el ISBN");
            }

        } else {
            cantlib = cantlib + 1;
            cantlibtot = cantlibtot + 1;
            if (adq == 1) {

                L[cantlib][1] = jTextFieldnombremat.getText();
                L[cantlib][2] = jTextFieldcoda.getText();
                int q = 1;
                int trololo = 1;
                while (trololo == 1 & q <= cantED) {

                    System.out.println("" + q);
                    System.out.println("" + cantED);
                    if (jTextFieldcoda.getText().equals(ED[q][2])) {
                        trololo = 0;
                    }
                    q++;
                }

                switch (mat) {
                    case 0:
                        CANTMATE[1] = CANTMATE[1] + 1;
                        L[cantlib][3] = "Libro";
                        LG[cantlibtot][3] = "Libro";
                        break;
                    case 1:
                        CANTMATE[2] = CANTMATE[2] + 1;
                        L[cantlib][3] = "Revista";
                        LG[cantlibtot][3] = "Revista";
                        break;
                    case 2:
                        CANTMATE[3] = CANTMATE[3] + 1;
                        L[cantlib][3] = "Monografia";
                        LG[cantlibtot][3] = "Monografia";
                        break;

                }
                L[cantlib][5] = jTextFieldaño.getText();
                while (Integer.parseInt(jTextFieldaño.getText()) < 0 || Integer.parseInt(jTextFieldaño.getText()) > 2017) {
                    L[cantlib][5] = JOptionPane.showInputDialog("el año es invalido por favor vuelva a ingresarlo");
                }
                L[cantlib][6] = jTextFieldeditorial.getText();
                L[cantlib][7] = Integer.toString(jComboBoxestado.getSelectedIndex());
                while (L[cantlib][7].equals(2)) {
                    JOptionPane.showMessageDialog(null, "no se puede comprar algo en mal estado");
                    L[cantlib][7] = Integer.toString(jComboBoxestado.getSelectedIndex());
                }
                if (L[cantlib][7].equals(1)) {
                    L[cantlib][7] = "Bueno";
                }

                if (trololo == 1) {
                    //esto es para un nuevo editor
                    cantED++;
                    ED[cantED][2] = L[cantlib][2];
                    JOptionPane.showMessageDialog(null, "el codigo no fue encontrado, se procedera a ingresar este nuevo autor");
                    ED[cantED][1] = JOptionPane.showInputDialog("Por favor, ingrese el nombre del autor");
                }
                int cod = Integer.parseInt(jTextFieldcoda.getText());
                m = (Math.random() * 10);//desde aqui 
                a1 = Integer.toString((int) m);
                m = (Math.random() * 10);
                a2 = Integer.toString((int) m);
                m = (Math.random() * 10);
                a3 = Integer.toString((int) m);
                n2 = (cod / 10000) % 10;
                n3 = (cod / 1000) % 10;
                n4 = (cod / 100) % 10;
                n5 = (cod / 10) % 10;
                n6 = (cod % 10);
                n7 = Integer.parseInt(a1);
                n8 = Integer.parseInt(a2);
                n9 = Integer.parseInt(a3);
                r = (mat * 10) + (n2 * 9) + (n3 * 8) + (n4 * 7) + (n5 * 6) + (n6 * 5) + (n7 * 4) + (n8 * 3) + (n9 * 2);
                n10 = Math.abs(r % 11 - 11);
                System.out.println("" + r);

                if (n10 != 10) {
                    L[cantlib][4] = Integer.toString(mat) + Integer.toString(n2) + Integer.toString(n3)
                            + Integer.toString(n4) + Integer.toString(n5) + Integer.toString(n6)
                            + Integer.toString(n7) + Integer.toString(n8) + Integer.toString(n9) + Integer.toString(n10);
                    JOptionPane.showMessageDialog(null, "operacion exitosa el codigo asignado es:" + L[cantlib][4]);
                } else {
                    L[cantlib][4] = Integer.toString(mat) + Integer.toString(n2) + Integer.toString(n3) + Integer.toString(n4) + Integer.toString(n5) + Integer.toString(n6) + Integer.toString(n7) + Integer.toString(n8) + Integer.toString(n9) + "x";
                    JOptionPane.showMessageDialog(null, "operacion exitosa el codigo asignado es:" + L[cantlib][4]);
                }//hasta aqui creo el isbn
                //aqui agrego la matriz de los generales
                LG[cantlibtot][1] = jTextFieldnombremat.getText();
                LG[cantlibtot][2] = jTextFieldcoda.getText();

                LG[cantlibtot][4] = L[cantlib][4];
                LG[cantlibtot][5] = txtcant.getText();
            } else if (adq == 2) {
                //aqui va canje
                int existe = 1, bandera = 1;
                String isbn, cont;
                while (existe == 1 || bandera == 1) {
                    isbn = JOptionPane.showInputDialog("Por favor ingrese el ISBN del material a canjear");
                    cont = JOptionPane.showInputDialog("Por favor ingrese el ISBN la cantidad de material a canjear");
                    while (Integer.parseInt(cont) <= 0) {
                        cont = JOptionPane.showInputDialog("Cantidad no valida,Por favor vuelva ingrese el ISBN la cantidad de material a canjear");
                    }
//para aclarar 1 es falso y 2 verdadero.
                    for (int i = 1; i <= cantlibtot; i++) {
                        System.out.println("" + LG[i][4]);
                    }
                    for (int i = 1; i <= cantlibtot; i++) {
                        System.out.println(LG[i][4]);
                        System.out.println(isbn);
                        if ((LG[i][4]).equals((isbn)) ){
                            existe = 2;

                            if (Integer.parseInt(LG[i][5]) < Integer.parseInt(cont)) {
                                bandera = 1;

                            } else {
                                bandera = 2;
                                if (Integer.parseInt(LG[i][5]) == Integer.parseInt(cont)) {
                                    for (int j = i; j <= cantlibtot; j++) {
                                        for (int r = 1; r <= 5; r++) {
                                            LG[j][r] = LG[j + 1][r];
                                        }
                                    }
                                    cantlibtot--;
                                } else {
                                    LG[i][5] = Integer.toString((Integer.parseInt(LG[i][5])) - (Integer.parseInt(cont)));
                                }
                                int l = 1, bandera2;
                                while (l <= Integer.parseInt(cont)) {
                                    bandera2 = 1;
                                    int p = 1;
                                    while (bandera2 == 1 & p <= cantlib) {
                                        if (isbn.equals(L[p][4]) ) {
                                            bandera2 = 2;

                                            for (int h = 1; h <= cantlib; h++) {
                                                for (int k = 1; k <= 7; k++) {
                                                    L[h][k] = L[h + 1][k];
                                                }
                                            }
                                            cantlib--;
                                        }
                                        p++;
                                    }
                                    l++;
                                }//fmq
                            }

                        }
                    }
                    if (existe == 2 & bandera == 2) {
                        cantlibtot++;
                        cantlib++;
                        LG[cantlibtot][1] = jTextFieldnombremat.getText();
                        L[cantlib][1] = jTextFieldnombremat.getText();
                        LG[cantlibtot][2] = jTextFieldcoda.getText();
                        L[cantlib][2] = jTextFieldcoda.getText();

                        switch (mat) {
                            case 0:
                                CANTMATE[1] = CANTMATE[1] + 1;
                                L[cantlib][3] = "Libro";
                                LG[cantlibtot][3] = "Libro";
                                break;
                            case 1:
                                CANTMATE[2] = CANTMATE[2] + 1;
                                L[cantlib][3] = "Revista";
                                LG[cantlibtot][3] = "Revista";
                                break;
                            case 2:
                                CANTMATE[3] = CANTMATE[3] + 1;
                                L[cantlib][3] = "Monografia";
                                LG[cantlibtot][3] = "Monografia";
                                break;

                        }
                        int cod = Integer.parseInt(jTextFieldcoda.getText());
                        m = (Math.random() * 10);//desde aqui 
                        a1 = Integer.toString((int) m);
                        m = (Math.random() * 10);
                        a2 = Integer.toString((int) m);
                        m = (Math.random() * 10);
                        a3 = Integer.toString((int) m);
                        n2 = (cod / 10000) % 10;
                        n3 = (cod / 1000) % 10;
                        n4 = (cod / 100) % 10;
                        n5 = (cod / 10) % 10;
                        n6 = (cod % 10);
                        n7 = Integer.parseInt(a1);
                        n8 = Integer.parseInt(a2);
                        n9 = Integer.parseInt(a3);
                        r = (mat * 10) + (n2 * 9) + (n3 * 8) + (n4 * 7) + (n5 * 6) + (n6 * 5) + (n7 * 4) + (n8 * 3) + (n9 * 2);
                        n10 = Math.abs(r % 11 - 11);
                        System.out.println("" + r);

                        if (n10 != 10) {
                            L[cantlib][4] = Integer.toString(mat) + Integer.toString(n2) + Integer.toString(n3)
                                    + Integer.toString(n4) + Integer.toString(n5) + Integer.toString(n6)
                                    + Integer.toString(n7) + Integer.toString(n8) + Integer.toString(n9) + Integer.toString(n10);
                            JOptionPane.showMessageDialog(null, "operacion exitosa el codigo asignado es:" + L[cantlib][4]);
                            LG[cantlibtot][4] = L[cantlib][4];
                        } else {
                            L[cantlib][4] = Integer.toString(mat) + Integer.toString(n2) + Integer.toString(n3) + Integer.toString(n4) + Integer.toString(n5) + Integer.toString(n6) + Integer.toString(n7) + Integer.toString(n8) + Integer.toString(n9) + "x";
                            JOptionPane.showMessageDialog(null, "operacion exitosa el codigo asignado es:" + L[cantlib][4]);
                            LG[cantlibtot][4] = L[cantlib][4];
                        }
                        LG[cantlibtot][5] = txtcant.getText();
                        L[cantlib][5] = jTextFieldaño.getText();
                        L[cantlib][6] = jTextFieldeditorial.getText();
                        if (est == 1) {
                            L[cantlib][7] = "Bueno";
                        } else if (est == 2) {
                            L[cantlib][7] = "Malo";
                        }
                    }
                    if (existe == 1) {
                        JOptionPane.showMessageDialog(null, "el codigo no fue encontrado");
                    }
                    if (bandera == 1) {
                        JOptionPane.showMessageDialog(null, "no hay suficiente para prestar");
                    }
                }
            } else if (adq == 3) {
                //aqui va donaciones

                L[cantlib][1] = jTextFieldnombremat.getText();
                L[cantlib][2] = jTextFieldcoda.getText();
                int q = 1;
                int trololo = 1;
                while (trololo == 1 & q <= cantED) {

                    System.out.println("" + q);
                    System.out.println("" + cantED);
                    if (jTextFieldcoda.getText().equals(ED[q][2])) {
                        trololo = 0;
                    }
                    q++;
                }

                switch (mat) {
                    case 0:
                        CANTMATE[1] = CANTMATE[1] + 1;
                        L[cantlib][3] = "Libro";
                        LG[cantlibtot][3] = "Libro";
                        break;
                    case 1:
                        CANTMATE[2] = CANTMATE[2] + 1;
                        L[cantlib][3] = "Revista";
                        LG[cantlibtot][3] = "Revista";
                        break;
                    case 2:
                        CANTMATE[3] = CANTMATE[3] + 1;
                        L[cantlib][3] = "Monografia";
                        LG[cantlibtot][3] = "Monografia";
                        break;

                }
                L[cantlib][5] = jTextFieldaño.getText();
                while (Integer.parseInt(jTextFieldaño.getText()) < 0 || Integer.parseInt(jTextFieldaño.getText()) > 2017) {
                    L[cantlib][5] = JOptionPane.showInputDialog("el año es invalido por favor vuelva a ingresarlo");
                }
                L[cantlib][6] = jTextFieldeditorial.getText();
                if (est == 1) {
                    L[cantlib][7] = "Bueno";
                } else if (est == 2) {
                    L[cantlib][7] = "Malo";
                }
                if (trololo == 1) {
                    //esto es para un nuevo editor
                    cantED++;
                    ED[cantED][2] = L[cantlib][2];
                    JOptionPane.showMessageDialog(null, "el codigo no fue encontrado, se procedera a ingresar este nuevo autor");
                    ED[cantED][1] = JOptionPane.showInputDialog("Por favor, ingrese el nombre del autor");
                }
                int cod = Integer.parseInt(jTextFieldcoda.getText());
                m = (Math.random() * 10);//desde aqui 
                a1 = Integer.toString((int) m);
                m = (Math.random() * 10);
                a2 = Integer.toString((int) m);
                m = (Math.random() * 10);
                a3 = Integer.toString((int) m);
                n2 = (cod / 10000) % 10;
                n3 = (cod / 1000) % 10;
                n4 = (cod / 100) % 10;
                n5 = (cod / 10) % 10;
                n6 = (cod % 10);
                n7 = Integer.parseInt(a1);
                n8 = Integer.parseInt(a2);
                n9 = Integer.parseInt(a3);
                r = (mat * 10) + (n2 * 9) + (n3 * 8) + (n4 * 7) + (n5 * 6) + (n6 * 5) + (n7 * 4) + (n8 * 3) + (n9 * 2);
                n10 = Math.abs(r % 11 - 11);
                System.out.println("" + r);

                if (n10 != 10) {
                    L[cantlib][4] = Integer.toString(mat) + Integer.toString(n2) + Integer.toString(n3)
                            + Integer.toString(n4) + Integer.toString(n5) + Integer.toString(n6)
                            + Integer.toString(n7) + Integer.toString(n8) + Integer.toString(n9) + Integer.toString(n10);
                    JOptionPane.showMessageDialog(null, "operacion exitosa el codigo asignado es:" + L[cantlib][4]);
                } else {
                    L[cantlib][4] = Integer.toString(mat) + Integer.toString(n2) + Integer.toString(n3) + Integer.toString(n4) + Integer.toString(n5) + Integer.toString(n6) + Integer.toString(n7) + Integer.toString(n8) + Integer.toString(n9) + "x";
                    JOptionPane.showMessageDialog(null, "operacion exitosa el codigo asignado es:" + L[cantlib][4]);
                }//hasta aqui creo el isbn
                //aqui agrego la matriz de los generales
                LG[cantlibtot][1] = jTextFieldnombremat.getText();
                LG[cantlibtot][2] = jTextFieldcoda.getText();

                LG[cantlibtot][4] = L[cantlib][4];
                LG[cantlibtot][5] = txtcant.getText();

            }

        }


    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        menu a = new menu();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adquisiciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adquisiciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adquisiciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adquisiciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adquisiciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JComboBox<String> jComboBoxadq;
    private javax.swing.JComboBox<String> jComboBoxestado;
    private javax.swing.JComboBox<String> jComboBoxmaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelaño;
    private javax.swing.JLabel jLabeleditoria;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldaño;
    private javax.swing.JTextField jTextFieldcoda;
    private javax.swing.JTextField jTextFieldeditorial;
    private javax.swing.JTextField jTextFieldnombremat;
    private javax.swing.JTextField txtcant;
    // End of variables declaration//GEN-END:variables
}
