/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import javax.swing.table.DefaultTableModel;
import static ventanas.administrador.*;

/**
 *
 * @author Manlio Tejeda Gutie
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mitabla1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mitabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "autor", "Tipo", "ISBNl", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(mitabla1);

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("menu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*mostrar.append("nombre|autor|tipo|ISBN|año|edad|estado\n");
        for (int i = 1; i <= cantlib; i++) {
            mostrar.append(L[i][1] + "|" + L[i][2] + "|" + L[i][3] + "|" + L[i][4] + "|" + L[i][5] + "|" + L[i][6] + "|" + L[i][7] + "|\n");
        }
        for (int j = 1; j <= 3; j++) {
            mostrar.append(CANTMATE[j] + "\n");
        }
        for (int j = 0; j <=cantED; j++) {
             System.out.println(""+ED[j][1]+"|"+ED[j][2]+"\n");
        }*/
        DefaultTableModel modelo = (DefaultTableModel) mitabla1.getModel();
        int filas = modelo.getRowCount();
        for (int j = 1; j <= filas; j++) {
            modelo.removeRow(0);
        }
        for (int i = 1; i <= cantlib; i++) {

            modelo.addRow(new Object[]{LG[i][1], LG[i][2], LG[i][3], LG[i][4], LG[i][5]});
        }
        // http://panamahitek.com/agregar-filas-a-un-jtable-en-java/ aqui esta todo


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: 
       /* String aux, aux2, aux3, aux4, aux5, aux6, aux7;
        int i;
        for (int k = 1; k <= cantlib; k++) {

            aux = L[k][1];
            aux2 = L[k][2];
            aux3 = L[k][3];
            aux4 = L[k][4];
            aux5 = L[k][5];
            aux6 = L[k][6];
            aux7 = L[k][7];
            i = k - 1;
            while (i >= 0 & Integer.parseInt(aux4).equals(Integer.parseInt( L[i][4]))) {

                L[i + 1][4] = L[i][4];

                L[i + 1][1] = L[i][1];

                L[i + 1][3] = L[i][3];

                L[i + 1][5] = L[i][5];

                L[i + 1][2] = L[i][2];

                L[i + 1][6] = L[i][6];

                L[i + 1][7] = L[i][7];
                i = i - 1;
            }
            L[i + 1][1] = aux;
            L[i + 1][2] = aux2;
            L[i + 1][3] = aux3;
            L[i + 1][4] = aux4;
            L[i + 1][5] = aux5;
            L[i + 1][6] = aux6;
            L[i + 1][7] = aux7;
        }

        for (int k = 1; k <= cantlibtot; k++) {
            aux = LG[k][1];
            aux2 = LG[k][2];
            aux3 = LG[k][3];
            aux4 = LG[k][4];
            aux5 = LG[k][5];

            i = k - 1;
            while (i >= 0 & aux == LG[i][4]) {

                LG[i + 1][4] = LG[i][4];

                LG[i + 1][1] = LG[i][1];

                LG[i + 1][3] = LG[i][3];

                LG[i + 1][5] = LG[i][5];

                LG[i + 1][2] = LG[i][2];
                i--;
            }
            LG[i + 1][1] = aux;
            LG[i + 1][2] = aux2;
            LG[i + 1][3] = aux3;
            LG[i + 1][4] = aux4;
            LG[i + 1][5] = aux5;
            DefaultTableModel modelo = (DefaultTableModel) mitabla1.getModel();
            int filas = modelo.getRowCount();
            for (int j = 1; j <= filas; j++) {
                modelo.removeRow(0);
            }
            for ( i = 1; i <= cantlib; i++) {
                modelo.addRow(new Object[]{LG[i][1], LG[i][2], LG[i][3], LG[i][4], L[i][5], LG[i][6]});
            }

        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         menu a = new menu();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mitabla1;
    // End of variables declaration//GEN-END:variables
}
